<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,0,'6ZuF6YCC5ZOB54mM');
$cfg_Cs[2]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[3]=array(2,1,1,'6ZuF6YCC5peg6LC36bKc6IKJ57Ku');
$cfg_Cs[4]=array(2,1,1,'6ZuF6YCC5YWo5pyf54yr57Ku');
$cfg_Cs[5]=array(2,1,1,'6ZuF6YCC5Y6f5ZGz6LGG6IWQ54yr56CC');
$cfg_Cs[6]=array(2,1,1,'6ZuF6YCC6YeR5p6q6bG8572Q5aS0');
$cfg_Cs[7]=array(0,1,1,'5oiY55Wl5ZCI5L2c');
$cfg_Cs[8]=array(0,1,1,'5YWz5LqO6ZuF6YCC');
$cfg_Cs[9]=array(0,1,1,'6ZuF6YCC6K++5aCC');
$cfg_Cs[10]=array(0,1,1,'6IGU57O75oiR5Lus');
?>