<div class="news_wrapper">		  
				<div class="newsbody">
				  <p class="date"><span class="year">[field:pubdate function='strftime("%m-%d",@me)'/]</span><span class="md">[field:pubdate function='strftime("%Y",@me)'/]</span></p>
				  <p class="title"><a href="[field:arcurl/]"  target="_black" >[field:title/]</a></p>
				  <div class="separator"></div>
				  <p class="description"><a href="[field:arcurl/]"  target="_black" >[field:description/]……</a></p>
				 
				</div>
				 <a href="[field:arcurl/]"  target="_black" ><img class="newsimg" src="[field:litpic/]"/></a>
			  </div>