<div class="news_wrapper">		  
				<div class="newsbody">
				  <p class="date"><span class="year">08-03</span><span class="md">2016</span></p>
				  <p class="title">[field:title/]</p>
				  <div class="separator"></div>
				  <p class="description">中国有句俗语：十年树木，百年树人。揭示了教育的根本价值，就是给国家提供具有崇高信仰、道德高尚、诚实守法、技艺精湛、博学多才、多专多能的人才，为国、为家、为社会创造科学知识和物质财富</p>
				</div>
				 <img class="newsimg" src="http://resources.jsmo.xin/templates/upload/462/201608/1470286474581.jpg"/>
			  </div>