<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("title","",266,280);
$z[3]=Array("arcurl","",292,307);
$z[4]=Array("title","",327,341);
$z[5]=Array("arcurl","",428,443);
$z[6]=Array("description","",463,483);
$z[7]=Array("arcurl","",535,550);
$z[8]=Array("litpic","",726,741);

?>