<div class="news_wrapper">
	<!--             <a href="/" target="_blank"><img class="newsimg" src="http://resources.jsmo.xin/templates/upload/462/201608/1470286474581.jpg"/></a> -->
					<div class="newsbody">
						<p class="date"><span class="year">[field:pubdate function='strftime("%m-%d",@me)'/]</span><span class="md">[field:pubdate function='strftime("%Y",@me)'/]</span></p>
						<h2 class="title"><a href="hrr[field:arcurl/]" target="_blank">[field:title/]</a></h2>
						<p class="description"><a href="[field:arcurl/]" target="_blank">[field:description/]……</a></p>
					</div>
				</div>