<div class="news_wrapper">		  
				<div class="newsbody">
				  <p class="date"><span class="year">[field:pubdate function='strftime("%m-%d",@me)'/]</span><span class="md">[field:pubdate function='strftime("%Y",@me)'/]</span></p>
				  <p class="title"><a href="[field:arcurl/]">[field:title/]</a></p>
				  <div class="separator"></div>
				  <p class="description">[field:description/]……</p>
				  <p class="description">xiangxi</p>
				</div>
				 <a href="[field:arcurl/]"><img class="newsimg" src="[field:litpic/]"/></a>
			  </div>