<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("title","",320,334);
$z[3]=Array("arcurl","",346,361);
$z[4]=Array("title","",381,395);
$z[5]=Array("arcurl","",482,497);
$z[6]=Array("description","",517,537);
$z[7]=Array("arcurl","",589,604);
$z[8]=Array("litpic","",780,795);

?>