<div class="news_wrapper">
	<!--             <a href="/" target="_blank"><img class="newsimg" src="http://resources.jsmo.xin/templates/upload/462/201608/1470286474581.jpg"/></a> -->
					<div class="newsbody">
						<p class="date"><span class="year">08-03</span><span class="md">2016</span></p>
						<h2 class="title"><a href="/" target="_blank">[field:title/]</a></h2>
						<p class="description"><a href="/" target="_blank">[field:description/]……</a></p>
					</div>
				</div>