<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("title","",334,348);
$z[3]=Array("arcurl","",360,375);
$z[4]=Array("title","",395,409);
$z[5]=Array("arcurl","",496,511);
$z[6]=Array("description","",531,551);
$z[7]=Array("arcurl","",603,618);
$z[8]=Array("litpic","",794,809);

?>