<div class="news_wrapper">		  
				<div class="newsbody">
				  <p class="date"><span class="year">08-03</span><span class="md">2016</span></p>
				  <p class="title">[field:title/]</p>
				  <div class="separator"></div>
				  <p class="description">[field:description/]</p>
				</div>
				 <img class="newsimg" src="http://resources.jsmo.xin/templates/upload/462/201608/1470286474581.jpg"/>
			  </div>