<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("click","</i></p>\r\n					  <p class=\"title\" title=\"[field:title",292,373);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",385,400);
$z[4]=Array("title","",420,434);
$z[5]=Array("arcurl","",521,536);
$z[6]=Array("description","",556,576);
$z[7]=Array("arcurl","",628,643);
$z[8]=Array("litpic","",819,834);

?>