<?php
$z[0]=Array("field","",182,205);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",246,268);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",306,364);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("global","",584,616);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",671,703);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1243,1275);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","'  data-am-scrollspy=\"{animation: 'fade', delay: 100}\">\r\n  <ul class=\"am-slides\">\r\n      <li>\r\n          <img src=\"{dede:global.cfg_templets_skin",1816,2154);
$z[6][4]['filename']="head.htm";
$z[6][4]['/ </div> </div> </div> </header> <div data-am-widget']="slider";
$z[6][4]['class']="am-slider am-slider-a1";
$z[6][4]['data-am-slider']="{\"directionNav\":false";
$z[7]=Array("global","",3863,3895);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",3965,3997);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",4074,4106);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",4184,4216);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",4632,4664);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",4707,4739);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",4779,4811);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("global","",4858,4890);
$z[14][4]['name']="cfg_templets_skin";

?>