<?php
$z[0]=Array("global","",163,195);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("field","",300,323);
$z[1][4]['name']="seotitle";
$z[2]=Array("field","",364,386);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",424,482);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",905,940);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",8368,8405);
$z[5][4]['filename']="footer.htm";

?>