<div class="news_wrapper">		  
				<div class="newsbody">
				  <p class="date"><span class="year">{dede:field.pubdate function="MyDate('m-d',@me)"/}</span><span class="md">{dede:field.pubdate function="MyDate('Y',@me)"/}</span></p>
				  <p class="title">[field:title/]</p>
				  <div class="separator"></div>
				  <p class="description">[field:description/]……</p>
				</div>
				 <img class="newsimg" src="http://resources.jsmo.xin/templates/upload/462/201608/1470286474581.jpg"/>
			  </div>