<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("title","",345,359);
$z[3]=Array("arcurl","",371,386);
$z[4]=Array("title","",406,420);
$z[5]=Array("arcurl","",507,522);
$z[6]=Array("description","",542,562);
$z[7]=Array("arcurl","",614,629);
$z[8]=Array("litpic","",805,820);

?>