<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("title","",304,318);
$z[3]=Array("arcurl","",330,345);
$z[4]=Array("title","",365,379);
$z[5]=Array("arcurl","",466,481);
$z[6]=Array("description","",501,521);
$z[7]=Array("arcurl","",573,588);
$z[8]=Array("litpic","",764,779);

?>