<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("click"," </i></p>\r\n					  <p class=\"title\" title=\"[field:title",293,375);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",387,402);
$z[4]=Array("title","",422,436);
$z[5]=Array("arcurl","",523,538);
$z[6]=Array("description","",558,578);
$z[7]=Array("arcurl","",630,645);
$z[8]=Array("litpic","",821,836);

?>