<div class="news_wrapper">		  
					<div class="newsbody">
					  <p class="date"><span class="year">[field:pubdate function='strftime("%m-%d",@me)'/]</span><span class="md">[field:pubdate function='strftime("%Y",@me)'/]</span> <i class="icon iconfont icon-yuedu" style="color:#cccccc;"> 　[field:click runphp="yes"] </i></p>
					  <p class="title" title="[field:title/]" ><a href="[field:arcurl/]"  target="_black" >[field:title/]</a></p>
					  <div class="separator"></div>
					  <p class="description"><a href="[field:arcurl/]"  target="_black" >[field:description/]……</a></p>
					 
					</div>
					 <a href="[field:arcurl/]"  target="_black" alt="雅适猫粮、雅适猫砂、猫粮、猫砂" title="猫粮怎么选择，猫砂怎么选择，猫罐头怎么选择……" ><img class="newsimg" src="[field:litpic/]"/></a>
				  </div>