<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("click","",293,307);
$z[3]=Array("title","",349,363);
$z[4]=Array("arcurl","",375,390);
$z[5]=Array("title","",410,424);
$z[6]=Array("arcurl","",511,526);
$z[7]=Array("description","",546,566);
$z[8]=Array("arcurl","",618,633);
$z[9]=Array("litpic","",809,824);

?>