<?php
$z[0]=Array("pubdate","",103,152);
$z[0][4]['function']="strftime(\"%m-%d\",@me)";
$z[1]=Array("pubdate","",176,222);
$z[1][4]['function']="strftime(\"%Y\",@me)";
$z[2]=Array("title","",333,347);
$z[3]=Array("arcurl","",359,374);
$z[4]=Array("title","",394,408);
$z[5]=Array("arcurl","",495,510);
$z[6]=Array("description","",530,550);
$z[7]=Array("arcurl","",602,617);
$z[8]=Array("litpic","",793,808);

?>