<?php
$z[0]=Array("global","",173,205);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",621,653);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",712,744);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",794,826);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",866,898);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",943,975);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1024,1056);
$z[6][4]['name']="cfg_templets_skin";

?>