<?php
$z[0]=Array("global","",131,163);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",411,436);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a> ",568,651);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\" >[field:typename/]</a>",855,998);
$z[3][4]['typeid']="3";
$z[4]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\" >[field:typename/]</a>",1013,1156);
$z[4][4]['typeid']="4";
$z[5]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\">[field:typename/]</a>",1171,1313);
$z[5][4]['typeid']="5";
$z[6]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\">[field:typename/]</a>",1328,1470);
$z[6][4]['typeid']="6";
$z[7]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",1600,1725);
$z[7][4]['typeid']="9";
$z[8]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",1835,1960);
$z[8][4]['typeid']="8";
$z[9]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",2070,2195);
$z[9][4]['typeid']="7";
$z[10]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",2305,2431);
$z[10][4]['typeid']="10";

?>