<?php
$z[0]=Array("global","",415,440);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a> ",572,655);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\" >[field:typename/]</a>",859,1002);
$z[2][4]['typeid']="3";
$z[3]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\" >[field:typename/]</a>",1017,1160);
$z[3][4]['typeid']="4";
$z[4]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\">[field:typename/]</a>",1175,1317);
$z[4][4]['typeid']="5";
$z[5]=Array("type","<a href=\"[field:typeurl/]\" class=\"active\" title=\"[field:typename/]_雅适宠物用品\">[field:typename/]</a>",1332,1474);
$z[5][4]['typeid']="6";
$z[6]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",1604,1729);
$z[6][4]['typeid']="9";
$z[7]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",1839,1964);
$z[7][4]['typeid']="8";
$z[8]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",2074,2199);
$z[8][4]['typeid']="7";
$z[9]=Array("type","<a href=\"[field:typeurl/]\" title=\"[field:typename/]_猫粮，猫砂\">[field:typename/]</a> ",2309,2435);
$z[9][4]['typeid']="10";

?>