<?php
$z[0]=Array("global","",134,160);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",200,222);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",259,317);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1852,1887);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\n          <div class=\"news_wrapper\">\n<!--             <a href=\"/\" target=\"_blank\"><img class=\"newsimg\" src=\"http://resources.jsmo.xin/templates/upload/462/201608/1470286474581.jpg\"/></a> -->\n            <div class=\"newsbody\">\n             <p class=\"date\"><span class=\"year\">[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span><span class=\"md\">[field:pubdate function='strftime(\"%Y\",@me)'/]</span></p>\n            <h2 class=\"title\"><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h2>\n            <a href=\"[field:arcurl/]\"><p class=\"description\">[field:description/]……</p></a>\n            </div>\n          </div>\n",7257,7936);
$z[4][4]['typeid']="9";
$z[4][4]['row']="9";

?>