<?php
$z[0]=Array("field","",334,357);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",398,420);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",458,516);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1005,1040);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",1659,1688);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n				  <div class=\"news_wrapper\">		  \r\n					<div class=\"newsbody\">\r\n					  <p class=\"date\"><span class=\"year\">[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span><span class=\"md\">[field:pubdate function='strftime(\"%Y\",@me)'/]</span> <i class=\"icon iconfont icon-yuedu\" style=\"color:#cccccc;\"> 　[field:click/] </i></p>\r\n					  <p class=\"title\" title=\"[field:title/]\" ><a href=\"[field:arcurl/]\"  target=\"_black\" >[field:title/]</a></p>\r\n					  <div class=\"separator\"></div>\r\n					  <p class=\"description\"><a href=\"[field:arcurl/]\"  target=\"_black\" >[field:description/]……</a></p>\r\n					 \r\n					</div>\r\n					 <a href=\"[field:arcurl/]\"  target=\"_black\" alt=\"雅适猫粮、雅适猫砂、猫粮、猫砂\" title=\"猫粮怎么选择，猫砂怎么选择，猫罐头怎么选择……\" ><img class=\"newsimg\" src=\"[field:litpic/]\"/></a>\r\n				  </div>  \r\n			",1784,2681);
$z[5][4]['pagesize']="10";
$z[6]=Array("pagelist","",2966,3030);
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="list_size";
$z[7]=Array("include","",3069,3106);
$z[7][4]['filename']="footer.htm";

?>