<?php
$z[0]=Array("field","",123,146);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",187,209);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",247,305);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1856,1891);
$z[3][4]['filename']="head.htm";
$z[4]=Array("list","\r\n          <div class=\"news_wrapper\">\r\n            <div class=\"newsbody\">\r\n              <p class=\"title\"><a href=\"[field:arcurl/]\" >[field:title/]</a></p>\r\n               <p class=\"date\">[field:pubdate function='strftime(\"%m-%d\",@me)'/] [field:pubdate function='strftime(\"%Y\",@me)'/]</p>\r\n            </div>\r\n             <a href=\"[field:arcurl/]\" ><img class=\"newsimg\" src=\"[field:litpic/]\"/></a>\r\n          </div>\r\n		",2319,2777);
$z[4][4]['pagesize']="10";
$z[5]=Array("pagelist","",2837,2901);
$z[5][4]['listitem']="pre,next,pageno";
$z[5][4]['listsize']="list_size";

?>