<?php
$z[0]=Array("global","",30,59);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",104,130);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",146,173);
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",195,225);
$z[3][4]['name']="cfg_description";
$z[4]=Array("global","",280,306);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",331,360);
$z[5][4]['name']="cfg_adminemail";
$z[6]=Array("arclist","\r\n<item>\r\n<title><![CDATA[[field:title/]]]></title>\r\n<link>[field:arcurl/]</link>\r\n<category>[field:typename/]</category>\r\n<pubdate>[field:pubdate function='strftime(\"%a,%d%b%Y%H:%M:%S +0800\",@me)'/]</pubdate>\r\n<description><![CDATA[[field:array runphp='yes']@me = (strpos(@me['litpic'],'defaultpic') ? \"\": \"<a [email=href='%7B@me[%22arcurl%22]%7D']href='{@me[\"arcurl\"]}'[/email] target='_blank'><img [email=src='%7B@me[%22litpic%22]%7D']src='{@me[\"litpic\"]}'[/email] border='0' /><br />\"); [/field:array][field:description function='html2text(@me)'/] ... ]]></description>\r\n</item>\r\n",374,1029);
$z[6][4]['row']="50";
$z[6][4]['orderby']="pubdate";
$z[6][4]['titlelen']="200";

?>