<?php
$z[0]=Array("global","",114,141);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("arclist","\r\n[field:pubdate function=strftime('%Y-%m-%d',@me)/]\r\n",158,275);
$z[1][4]['row']="1";
$z[1][4]['titlelen']="24";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("channel","\r\n<url>\r\n<loc>[field:typelink /]</loc>\r\n<changefreq>daily</changefreq>\r\n<priority>0.8</priority>\r\n</url>\r\n",355,509);
$z[2][4]['row']="6";
$z[2][4]['type']="top";
$z[3]=Array("arclist","\r\n<url>\r\n<loc>[field:arcurl/]</loc>\r\n<lastmod>[field:pubdate function=strftime('%Y-%m-%d',@me)/]</lastmod>\r\n<changefreq>monthly</changefreq>\r\n</url>\r\n",513,717);
$z[3][4]['row']="1000";
$z[3][4]['orderby']="pubdate";

?>